Update hanwckf.yml

diff --git a/.github/workflows/K2.yml b/.github/workflows/K2.yml
--- a/.github/workflows/K2.yml
+++ b/.github/workflows/K2.yml
@@ -1,203 +1,280 @@
-# Build TurBoTse's kernal4.4 Padavan
-
-name: build custom
+name: Build hanwckf's kernal3.x Padavan
 
 on:
   workflow_dispatch:
     inputs:
       target:
-        description: 'Select the router device'
-        required: true
         type: choice
+        description: 'target to compile'
         options:
-        - PSG1208
-        - PSG1218
-        default: PSG1218
-      toolchain:
-        description: 'Select the compilation toolchain'
-        required: true
-        type: choice
-        options:
-        - mipsel-linux-musl
-        - mipsel-linux-uclibc
-        default: mipsel-linux-musl
-      toolchaingcc:
-        description: 'Select the toolchain gcc version'
-        required: true
-        type: choice
-        options:
-        - mipsel-linux-musl
-        - mipsel-linux-musl-gcc7
-        - mipsel-linux-musl-gcc10
-        - mipsel-linux-uclibc
-        - mipsel-linux-uclibc-gcc7
-        - mipsel-linux-uclibc-gcc10
-        default: mipsel-linux-musl
-      cpufreq:
-        description: 'CPU Frequency (MHz)'
+        - Phicomm_K1
+        - Phicomm_K2
+        - Oyewifi_OYE-0001
+        - Lenovo_NEWIFI-MINI
+        - Xiaomi_MINI
+        - Xiaomi_3
+        - Xiaomi_3C
+        - Xiaomi_4
+        - Xiaomi_R3G
+        - Xiaomi_R4A
+        - Xiaomi_R3P
+        - Gee_HiWifi1S
+        - Gee_HiWifi2
+        - Gee_Enjoy1200
+        - Qihoo_360P2
+        - Xiaomi_NANO
+        - Meizu_R13
+        - Meizu_R13P
+        - Asus_RT-AC1200GU
+        - Xiaoyu_C1
+        - Xiaoyu_C3
+        - Xiaoyu_C5
+        - Youhua_WR1200JS
+        - Diting_NEWIFI3
+        - Gee_B70
+        - Totolink_A3004NS
+        - Phicomm_K2P
+        - Phicomm_K2P-USB
+        - JCG_836PRO
+        - JCG_AC860M
+        - DLINK_DIR-882
+        - DLINK_DIR-878
+        - Motorola_MR2600
+        - TP-LINK_WDR7300
+        - Redmi_AC2100
+        - Xiaomi_CR6606
+        - Xiaomi_CR6608
+        - Xiaomi_CR6609
+        - Xiaomi_AC2100
+        - JCG_Y2
+        - ZTE_E8820V2
+        - ZTE_E8820S
+        - Raisecom_MSG1500_X.00
+        - Netgear_R6220
+      uploadanon:
         type: boolean
-        default: false
-      mt7621_oc:
-        description: '1000Mhz=0x312 1100Mhz=0x362 1120Mhz=0x372 1200Mhz=0x3B2'
-        type: choice
-        options:
-        - '0x312'
-        - '0x362'
-        - '0x372'
-        - '0x3B2'
-      plugins:
-        description: 'String JSON list of plug-ins'
-        required: true
-        type: string
-        default: '{"ss":"y","v2ray":"n","xray":"y","trojan":"y","ssobfs":"y","smartdns":"y","vlmcsd":"y","ttyd":"n","iperf3":"n"}'
-      customization:
-        description: 'String JSON list of Customization'
-        required: true
-        type: string
-        default: '{"lanip":"192.168.2.1","signaccount":"admin","signpassword":"admin","wifi2gssid":"Padavan","wifi2gpsk":"1234567890","wifi5gssid":"Padavan-5G","wifi5gpsk":"1234567890"}'
-      nanoversion:
-        type: boolean
-        description: 'Compile the nano version'
-        default: false
-      oldreleases:
-        type: boolean
-        description: 'Delete old releases'
-        default: true
-      oldworkflow:
-        type: boolean
-        description: 'Delete old workflow runs'
-        default: true
+        description: 'upload firmware to anonfiles'
+        default: 'false'
 env:
+  REPOSITORY_URL: https://github.com/hanwckf/rt-n56u.git
+  TOOLCHAIN_URL: https://github.com/hanwckf/padavan-toolchain/releases/download/v1.1/mipsel-linux-uclibc.tar.xz
+  WORK_PATH: /opt/rt-n56u
+  TIME_ZONE: Asia/Shanghai
   FIRMWARE_AUTHOR: hanwckf
-  FIRMWARE_BRANCH: main
-  FIRMWARE_REPO: padavan
-  FIRMWARE_URL: https://github.com/hanwckf/rt-n56u.git
-  TOOLCHAIN_ROOT: toolchain/toolchain-mipsel
-  TOOLCHAIN_URL: https://github.com/TurBoTse/padavan/releases/download/toolchain
+  FIRMWARE_PATH: /opt/firmwares
 jobs:
   build:
-    runs-on: ubuntu-latest
-    env:
-      target: ${{ matrix.target }}
-      toolchain: ${{ matrix.toolchain }}
-      toolchaingcc: ${{ matrix.toolchaingcc }}
-    strategy:
-      matrix:
-        include:
-          - target: ${{ inputs.target }}
-            toolchain: ${{ inputs.toolchain }}
-            toolchaingcc: ${{ inputs.toolchaingcc }}
+    runs-on: ubuntu-20.04
+    if: github.event.repository.owner.id == github.event.sender.id
+
     steps:
-      - uses: actions/checkout@main
-      - uses: hendrikmuhs/ccache-action@main
-        with:
-          key: ${{ matrix.target }}-${{ matrix.toolchaingcc }}
-      - uses: actions/setup-go@main
-        with:
-          go-version: '1.22.3'
-          check-latest: true
-          cache: false
-      - name: Prepare environment
-        run: |
-          sudo apt-get update && sudo apt-get install -y libtool-bin gperf python3-docutils autopoint gettext ccache
-          echo "TRUNK_DIR=${{ github.workspace }}/$FIRMWARE_REPO/trunk" >> $GITHUB_ENV
-          echo "Compilation_time=$(TZ='Asia/Shanghai' date +%Y%m%d)" >> $GITHUB_ENV
-      - name: Download sources and toolchain
-        run: |
-          git clone --depth=1 $FIRMWARE_URL $FIRMWARE_REPO
-          mkdir -p $FIRMWARE_REPO/$TOOLCHAIN_ROOT
-          curl -fSsLo- $TOOLCHAIN_URL/${{ matrix.toolchaingcc }}.tar.xz | tar Jxv -C $FIRMWARE_REPO/$TOOLCHAIN_ROOT
-      - name: Parse the string JSON list
-        run: |
-          echo "lanip=${{fromJson(inputs.customization).lanip}}" >> $GITHUB_ENV
-          echo "signaccount=${{fromJson(inputs.customization).signaccount}}" >> $GITHUB_ENV
-          echo "signpassword=${{fromJson(inputs.customization).signpassword}}" >> $GITHUB_ENV
-          echo "wifi2gssid=${{fromJson(inputs.customization).wifi2gssid}}" >> $GITHUB_ENV
-          echo "wifi2gpsk=${{fromJson(inputs.customization).wifi2gpsk}}" >> $GITHUB_ENV
-          echo "wifi5gssid=${{fromJson(inputs.customization).wifi5gssid}}" >> $GITHUB_ENV
-          echo "wifi5gpsk=${{fromJson(inputs.customization).wifi5gpsk}}" >> $GITHUB_ENV
-          # plugins
-          echo "ss=${{fromJson(inputs.plugins).ss}}" >> $GITHUB_ENV
-          echo "v2ray=${{fromJson(inputs.plugins).v2ray}}" >> $GITHUB_ENV
-          echo "xray=${{fromJson(inputs.plugins).xray}}" >> $GITHUB_ENV
-          echo "trojan=${{fromJson(inputs.plugins).trojan}}" >> $GITHUB_ENV
-          echo "ssobfs=${{fromJson(inputs.plugins).ssobfs}}" >> $GITHUB_ENV
-          echo "smartdns=${{fromJson(inputs.plugins).smartdns}}" >> $GITHUB_ENV
-          echo "vlmcsd=${{fromJson(inputs.plugins).vlmcsd}}" >> $GITHUB_ENV
-          echo "ttyd=${{fromJson(inputs.plugins).ttyd}}" >> $GITHUB_ENV
-          echo "iperf3=${{fromJson(inputs.plugins).iperf3}}" >> $GITHUB_ENV
-      - name: Compile the nano version
-        if: ${{ github.event.inputs.nanoversion == 'true' }}
-        run: |
-          cd ${{ env.TRUNK_DIR }}/configs/templates
-          for M in ${{ matrix.target }}; do if [ -f $M.config ]; then
-            for MOD in ANTFS FAT EXFAT EXT2 EXT3 EXT4 XFS FUSE SWAP; do
-              sed -i "s/CONFIG_FIRMWARE_ENABLE_${MOD}=y/CONFIG_FIRMWARE_ENABLE_${MOD}=n/" $M.config; done
-            for MOD in UVC HID SERIAL AUDIO XFRM QOS IMQ IFB NFSD NFSC CIFS NTFS_3G LPRD U2EC TCPDUMP HDPARM PARTED SMBD WINS SMBD_SYSLOG FTPD RPL2TP EAP_PEAP HTTPS SFTP DROPBEAR_FAST_CODE OPENSSH OPENVPN SSWAN OPENSSL_EC OPENSSL_EXE XUPNPD MINIDLNA FIREFLY FFMPEG_NEW TRANSMISSION TRANSMISSION_WEB_CONTROL ARIA ARIA_WEB_CONTROL CURL SCUTCLIENT GDUT_DRCOM DOGCOM MINIEAP NJIT_CLIENT SOFTETHERVPN_SERVER SOFTETHERVPN_CLIENT SOFTETHERVPN_CMD VLMCSD TTYD LITE LRZSZ HTOP NANO IPERF3 DUMP1090 RTL_SDR MTR SOCAT SRELAY MENTOHUST FRPC FRPS REDSOCKS SHADOWSOCKS XRAY V2RAY TROJAN SSOBFS SINGBOX NAIVEPROXY ADBYBY DNSFORWARDER SMARTDNS ADGUARDHOME ZEROTIER ALIDDNS DDNSTO ALDRIVER SQM WIREGUARD; do
-              sed -i "s/CONFIG_FIRMWARE_INCLUDE_${MOD}=y/CONFIG_FIRMWARE_INCLUDE_${MOD}=n/" $M.config; done
-          fi; done
-      - name: Modify and customize
-        run: |
-          sed -i '/cp -f/d' $FIRMWARE_REPO/Makefile
-          # if [ -d custom/trunk ]; then cp -rf custom/trunk/* ${{ env.TRUNK_DIR }}/; fi
-          sh custom/scripts/setip.sh '${{ env.lanip }}' '${{ env.TRUNK_DIR }}/user/shared/src/defaults.h' '${{ env.TRUNK_DIR }}/user/www/dict/CN.dict'
-          sh custom/scripts/setaccount.sh '${{ env.signaccount }}' '${{ env.signpassword }}' '${{ env.TRUNK_DIR }}/user/shared/src/defaults.h'
-          sh custom/scripts/setwifi.sh '${{ env.wifi2gssid }}' '${{ env.wifi2gpsk }}' '${{ env.wifi5gssid }}' '${{ env.wifi5gpsk }}' '${{ env.TRUNK_DIR }}/user/shared/src/defaults.h'
-          cd ${{ env.TRUNK_DIR }}
-          if [ ! -f configs/templates/${{ matrix.target }}.config ]; then
-            echo "configs/templates/${{ matrix.target }}.config not found"
-          exit 0
-          fi
-          cp -f configs/templates/${{ matrix.target }}.config .config
-          # include plugin
-          echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=${{env.ss}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=${{env.v2ray}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_XRAY=${{env.xray}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=${{env.trojan}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=${{env.ssobfs}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=${{env.smartdns}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=${{env.vlmcsd}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_TTYD=${{env.ttyd}}" >> .config
-          echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=${{env.iperf3}}" >> .config
-          # cpufreq
-          if ${{ github.event.inputs.cpufreq == 'true' }}; then
-            echo "CONFIG_FIRMWARE_INCLUDE_OC=y" >> .config
-            echo "CONFIG_FIRMWARE_MT7621_OC=${{ inputs.mt7621_oc }}" >> .config
-          fi
-      - name: Start build firmware
-        run: |
-          cd $FIRMWARE_REPO
-          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
-          nano=""
-          if ${{ github.event.inputs.nanoversion == 'true' }}; then
-            nano="-nano"
-          fi
-          cpufreq=""
-          if ${{ github.event.inputs.cpufreq == 'true' }}; then
-            cpufreq="-cpufreq-${{ inputs.mt7621_oc }}"
-          fi
-          mkdir -p ${{ env.TRUNK_DIR }}/firmwares/
-          sudo mv ${{ env.TRUNK_DIR }}/images/*.trx ${{ env.TRUNK_DIR }}/firmwares/$FIRMWARE_AUTHOR-${{ matrix.target }}-3.4-${{ matrix.toolchaingcc }}${nano}${cpufreq}-${{ env.Compilation_time }}.trx
-      - uses: actions/upload-artifact@main
-        with:
-          name: ${{ matrix.target }}-${{ matrix.toolchaingcc }}
-          path: ${{ env.TRUNK_DIR }}/firmwares/*.trx
-      - uses: ncipollo/release-action@main
-        with:
-          commit: ${{ github.sha }}
-          tag: ${{ env.Compilation_time }}
-          artifacts: ${{ env.TRUNK_DIR }}/firmwares/*.trx
-          allowUpdates: true
-          omitBodyDuringUpdate: true
-      - uses: dev-drprasad/delete-older-releases@master
-        if: ${{ github.event.inputs.oldreleases == 'true' }}
-        with:
-          keep_latest: 1
-          delete_tags: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - uses: Mattraks/delete-workflow-runs@main
-        if: ${{ github.event.inputs.oldworkflow == 'true' }}
-        with:
-          retain_days: 0
-          keep_minimum_runs: 1
+    - uses: actions/checkout@v4
+    - uses: Bonnie2980/variable-mapper@master
+      id: export
+      with:
+        key: "${{ github.event.inputs.target }}"
+        map: |
+          {
+            "Phicomm_K1": {
+              "model": "PSG1208"
+            },
+            "Phicomm_K2": {
+              "model": "PSG1218"
+            },
+            "Oyewifi_OYE-0001": {
+              "model": "OYE-001"
+            },
+            "Lenovo_NEWIFI-MINI": {
+              "model": "NEWIFI-MINI"
+            },
+            "Xiaomi_MINI": {
+              "model": "MI-MINI"
+            },
+            "Xiaomi_3": {
+              "model": "MI-3"
+            },
+            "Xiaomi_3C": {
+              "model": "MI-3C"
+            },
+            "Xiaomi_4": {
+              "model": "MI-4"
+            },
+            "Xiaomi_R3G": {
+              "model": "MI-R3G"
+            },
+            "Xiaomi_R4A": {
+              "model": "MI-R4A"
+            },
+            "Xiaomi_R3P": {
+              "model": "MI-R3P"
+            },
+            "Gee_HiWifi1S": {
+              "model": "HC5661A"
+            },
+            "Gee_HiWifi2": {
+              "model": "HC5761A"
+            },
+            "Gee_Enjoy1200": {
+              "model": "HC5861B"
+            },
+            "Qihoo_360P2": {
+              "model": "360P2"
+            },
+            "Xiaomi_NANO": {
+              "model": "MI-NANO"
+            },
+            "Meizu_R13": {
+              "model": "MZ-R13"
+            },
+            "Meizu_R13P": {
+              "model": "MZ-R13P"
+            },
+            "Asus_RT-AC1200GU": {
+              "model": "RT-AC1200GU"
+            },
+            "Xiaoyu_C1": {
+              "model": "XY-C1"
+            },
+            "Xiaoyu_C3": {
+              "model": "XY-C1"
+            },
+            "Xiaoyu_C5": {
+              "model": "XY-C1"
+            },
+            "Youhua_WR1200JS": {
+              "model": "WR1200JS"
+            },
+            "Diting_NEWIFI3": {
+              "model": "NEWIFI3"
+            },
+            "Gee_B70": {
+              "model": "B70"
+            },
+            "Totolink_A3004NS": {
+              "model": "A3004NS"
+            },
+            "Phicomm_K2P": {
+              "model": "K2P"
+            },
+            "Phicomm_K2P-USB": {
+              "model": "K2P-USB"
+            },
+            "JCG_836PRO": {
+              "model": "JCG-836PRO"
+            },
+            "JCG_AC860M": {
+              "model": "JCG-AC860M"
+            },
+            "DLINK_DIR-882": {
+              "model": "DIR-882"
+            },
+            "DLINK_DIR-878": {
+              "model": "DIR-878"
+            },
+            "Motorola_MR2600": {
+              "model": "MR2600"
+            },
+            "TP-LINK_WDR7300": {
+              "model": "WDR7300"
+            },
+            "Redmi_AC2100": {
+              "model": "RM2100"
+            },
+            "Xiaomi_CR6606": {
+              "model": "CR660x"
+            },
+            "Xiaomi_CR6608": {
+              "model": "CR660x"
+            },
+            "Xiaomi_CR6609": {
+              "model": "CR660x"
+            },
+            "Xiaomi_AC2100": {
+              "model": "R2100"
+            },
+            "JCG_Y2": {
+              "model": "JCG-Y2"
+            },
+            "ZTE_E8820V2": {
+              "model": "E8820V2"
+            },
+            "ZTE_E8820S": {
+              "model": "ZTE_E8820S"
+            },
+            "Raisecom_MSG1500_X.00": {
+              "model": "MSG1500"
+            },
+            "Netgear_R6220": {
+              "model": "R6220"
+            },
+            ".*": {
+              "model": "K2P"
+            }
+          }
+        export_to: env
+        mode: first_match
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo apt-get update
+        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod \
+        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
+        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
+        sudo timedatectl set-timezone "$TIME_ZONE"
+    - name: Clone source code
+      run: |
+        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
+        cd $WORK_PATH/toolchain-mipsel
+        mkdir -p toolchain-3.4.x
+        wget $TOOLCHAIN_URL
+        tar -xvf mipsel-linux-uclibc.tar.xz -C toolchain-3.4.x
+    - name: Set environment variables
+      run: |
+        git config --global log.date format:'%Y%m%d'
+        cd $WORK_PATH
+        echo "FIRMWARE_VERSION=$(git log -1 --pretty=format:"%cd")" >> $GITHUB_ENV
+        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
+    - name: Custom config
+      run: |
+        cd $WORK_PATH/trunk
+        if [ ! -f configs/templates/${{ env.model }}.config ] ; then
+        echo "configs/templates/${{ env.model }}.config not found"
+        exit 1
+        fi
+        cp -f configs/templates/${{ env.model }}.config .config
+        sed -i "s/FIRMWARE_BUILDS_REV=.*/FIRMWARE_BUILDS_REV=${FIRMWARE_VERSION}/g" ./versions.inc
+    - name: Build firmware
+      run: |
+        cd $WORK_PATH/trunk
+        ./clear_tree
+        fakeroot ./build_firmware_modify ${{ env.model }}
+    - name: Organize firmware files
+      id: organize
+      run: |
+        mkdir -p $FIRMWARE_PATH/
+        cd $WORK_PATH/trunk/images
+        for firmwarefile in $(ls *.trx)
+        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"${{ env.model }}"_kernal3.x.trx"
+        done
+        cd $FIRMWARE_PATH
+        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+        echo "STATUS=success" >> $GITHUB_ENV
+    - name : Upload packages
+      uses: actions/upload-artifact@master
+      if: env.STATUS == 'success'
+      with:
+        name: Padavan-packages
+        path: ${{ env.FIRMWARE }}
+    - name: Upload firmware to anonfiles
+      if: env.STATUS == 'success' && github.event.inputs.uploadanon == 'true'
+      run: |
+        curl -fsSL git.io/file-transfer | sh
+        ./transfer anon --no-progress ${FIRMWARE} 2>&1 | tee anonfile.log
+        echo "::warning file=anonfile.com::$(cat anonfile.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")"
+    - name: Remove obsolete firmwares on artifacts
+      uses: Bonnie2980/gha-remove-artifacts@master
+      if: env.STATUS == 'success'
+      with:
+        age: '1 day'
+        skip-recent: 5
